### ISSUE TITLE
发现两个BUG,!!!!

### ISSUE THREAD

**Issue by tmige** [xinghanking/phpdav#8]
1、在nginx phpfpm工作方式下：
上传大文件，当文件大小超过PHP.ini中设置的memory_limit的设置时，
当上传数据完成，保存文件时：
Server.php文件的函数
public static function get_body()
    {
        return file_get_contents('php://input');
    }
    会报错，内存溢出，无法保存文件。

  2、在用./phpdav 启动方式下：
    上传文件没有问题，但出现：所有上传的.mp4，读取有问题。不能读取文件。
    应该是返回数据时，head头没处理好，
    且只有.mp4文件有问题，别的文件都是正常的。
    测试时，可以把任意文件改名为.mp4，可重现问题。

**Comment by tmige** [comment]
还说漏了一个BUG
在客户端当重命名目录，如果目录下有文件或子目录，会出来两个同的文件名和目录。应该是数据库中的旧记录没有删除。
重现问题：从客户端新建一个文件夹，并在文件夹中上传文。再把文件夹改名。刷新就可以重现问题。

**Comment by tmige** [comment]
修改了Server.php,目前测试没问题了！ 

/**
     * 保存上传的文件到指定路径
     * @param string $path
     * @return false|int
     */
    public static function save_data($path)
    {
        #return file_put_contents($path, self::get_body());
		$input = fopen("php://input", "r");
		$savefile = fopen($path,'w+');
		$realSize = stream_copy_to_stream($input, $savefile);
		fclose($input);
		fclose($savefile);
		return $realSize;
    }

**Comment by tmige** [comment]
目录重命名时，比如：重命名2323目录为5555时，原2323目录下面有文件，执行是会出以下错误：
Exception: 执行sql语句失败，sql:UPDATE `dav_resource` SET path='/www/share_disk/szxlc/5555',upper_id=4 WHERE (`path`='/www/share_disk/szxlc/2323') in /www/model/db/sqlite/Conn.php:197
Stack trace:
#0 /www/model/dav/Db.php(271): Db_Sqlite_Conn->exec('UPDATE `dav_res...')
#1 /www/model/dao/DavResource.php(383): Dav_Db->update(Array, Array)
#2 /www/model/dav/Resource.php(419): Dao_DavResource->move('/www/share_disk...', '/www/share_disk...', 'application/x-d...')
#3 /www/method/Move.php(56): Dav_Resource->move('/www/share_disk...')
#4 /www/model/dav/Method.php(36): Method_Move->handler()
#5 /www/model/dav/Server.php(41): Dav_Method->execute()
#6 /www/cgi/index.php(7): Dav_Server->start()
#7 {main}

**Comment by tmige** [comment]
目录重命名问题查明：
看一下数据库，每个目录重命名后，数据库更新下级资源时，多了"/"，

6	2021-08-03 08:22:00	5	/www/share_disk/szxlc/55556	application/x-director	0	0-6108f809	1627977737		4
7	2021-08-03 08:22:00	5	/www/share_disk/szxlc/2b1d0ab26bf4bb3e4f3e14d31238c8a.jpg	image/jpeg	4209280	403a80-6107659b	1627874715		4
8	2021-08-03 08:22:00	5	/www/share_disk/szxlc/IMG_20210502_141248.jpg	image/jpeg	1909887	1d247f-610783d9	1627882457		4
9	2021-08-03 08:22:00	5	/www/share_disk/szxlc/IMG_20210502_142749.jpg	image/jpeg	2281011	22ce33-610783cf	1627882447		4
10	2021-08-03 08:22:00	5	/www/share_disk/szxlc/IMG_20210502_153004.jpg	image/jpeg	2146191	20bf8f-610783b3	1627882419		4
11	2021-08-03 08:22:00	5	/www/share_disk/szxlc/mmexport1586166780423.jpg	image/jpeg	604613	939c5-61078622	1627883042		4
12	2021-08-03 08:22:00	5	/www/share_disk/szxlc/public_dir	application/x-director	0	0-6108f0a6	1627975846		4
13	2021-08-03 08:22:00	5	/www/share_disk/szxlc/ranking_bg.7c23a5e.png	image/png	64156	fa9c-61080900	1627916544		4
14	2021-08-03 08:22:00	5	/www/share_disk/szxlc/安装说明1.pdf	application/pdf	268255	417df-61080910	1627916560		4
15	2021-08-03 08:22:01	6	/www/share_disk/szxlc/55556///bee.yaml	text/plain	406	196-6108f809	1627977737		6
16	2021-08-03 08:23:07	6	/www/share_disk/szxlc/55556//bee.yaml	text/plain	406	196-6108f809	1627977737		6
17	2021-08-03 08:23:51	6	/www/share_disk/szxlc/public_dir/bee.yaml	text/plain	406	196-6108f0a7	1627975847		12
18	2021-08-03 08:40:31	6	/www/share_disk/szxlc/55556/bee.yaml	text/plain	406	196-6108f809	1627977737		6

**Comment by tmige** [comment]
目录重命名问题修正：
DavResource.php文件
找到public function move(){
}
修改下面代码
foreach ($pathInfoList as $info) {
                    //$path = $destination . DIRECTORY_SEPARATOR . substr($info['path'], strlen($sourceResource)); //原来问题代码，文件名多了一个'/'
			$path = $destination . DIRECTORY_SEPARATOR . substr($info['path'], strlen($sourceResource)+1); //修改后代码
                    $this->update(['path' => $path], ['id=' . $info['id']]);
                }

**Comment by chenziran111** [comment]
> 修改了Server.php,目前测试没问题了！
> 
> /**
> * 保存上传的文件到指定路径
> * @param string $path
> * @return false|int
> */
> public static function save_data($path)
> {
> #return file_put_contents($path, self::get_body());
> $input = fopen("php://input", "r");
> $savefile = fopen($path,'w+');
> $realSize = stream_copy_to_stream($input, $savefile);
> fclose($input);
> fclose($savefile);
> return $realSize;
> }

大佬牛逼

**Comment by xinghanking** [comment]
Thanks all, 问题已经修复。
